spring:
  application:
    name: user

  config:
    import: optional:file:./.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver # postgresql driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # postgresql dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

kakao:
  admin-key: ${KAKAO_ADMIN_KEY}

server:
  port: ${CONTAINER_PORT:8081} # 로컬에서 실행 시 8081, 도커에서 실행 시 8080

auth:
  host: ${AUTH_HOST:auth}
  port: ${CONTAINER_PORT:8080} # 로컬에서 실행 시 8080, 도커에서 실행 시 8080